const vocabulary = {
    en: {
        MONTH_1: 'January',
        MONTH_2: 'February',
        MONTH_3: 'March',
        MONTH_4: 'April',
        MONTH_5: 'May',
        MONTH_6: 'June',
        MONTH_7: 'July',
        MONTH_8: 'August',
        MONTH_9: 'September',
        MONTH_10: 'October',
        MONTH_11: 'November',
        MONTH_12: 'December',
        HOMEPAGE_SHARE_BY: 'SHARE YOUR RIDE BY',
        HOMEPAGE_LOGIN_STRAVA: 'LOGIN TO STRAVA',
        HOMEPAGE_OR: 'OR',
        HOMEPAGE_LOAD: 'LOAD A GPX',
        HOMEPAGE_PER: 'X',
        HOMEPAGE_BACK: '< BACK',
        HOMEPAGE_SELECT_ACTIVITY: 'SELECT AN ACTIVITY',
        HOMEPAGE_BEFORE_START: 'BEFORE YOU CAN START YOU HAVE TO LOAD SOME ACTIVITIES',
        BUTTON_TITLE: 'TITLE',
        BUTTON_DATE: 'DATE',
        BUTTON_DISTANCE: 'DISTANCE',
        BUTTON_DURATION: 'DURATION',
        BUTTON_MOVING_TIME: 'MOVING TIME',
        BUTTON_ELEVATION: 'ELEVATION',
        BUTTON_ELEVATION_GAIN: 'ELEVATION GAIN',
        BUTTON_AVERAGE: 'AVERAGE',
        BUTTON_PACE: 'PACE',
        BUTTON_AVERAGE_PACE: 'AVERAGE PACE',
        BUTTON_AVERAGE_SPEED: 'AVERAGE SPEED',
        BUTTON_POWER: 'POWER',
        BUTTON_AVERAGE_POWER: 'AVERAGE POWER',
        BUTTON_COORDINATES: 'COORDINATES',
        BUTTON_CALORIES: 'CALORIES',
        BUTTON_SWITCH: 'SWITCH TEXT',
        BUTTON_SWITCH_ALTITUDE: 'MOVE ALTITUDE',
        IMAGE_DISTANCE: 'Distance',
        IMAGE_DURATION: 'Duration',
        IMAGE_MOVING_TIME: 'Moving Time',
        IMAGE_ELEVATION: 'Elevation',
        IMAGE_ELEVATION_GAIN: 'Elevation Gain',
        IMAGE_AVERAGE: 'Average',
        IMAGE_PACE: 'Pace',
        IMAGE_AVERAGE_PACE: 'Avg Pace',
        IMAGE_AVERAGE_SPEED: 'Avg Speed',
        IMAGE_POWER: 'Power',
        IMAGE_AVERAGE_POWER: 'Avg Power',
        IMAGE_COORDINATES: 'Coordinates',
        IMAGE_CALORIES: 'Calories',
        NAME_APP: 'TRACELINER © ' + new Date().getFullYear(),
        CREATED_BY: 'Created with ❤️ by Giovanni Maggi',
        MODAL_TEXT: 'Pick your favorite version!',
        MODAL_GUIDE: 'The complete will have the background while the countour will have a trasparent background. Bare in mind that IG do not support sharing directly image with transparent background, you have to save in your library first.',
        MODAL_COMPLETE: 'COMPLETE',
        MODAL_CONTOUR: 'CONTOUR',
        MODAL_ERROR: 'Something went wrong, please regenerate the image!',
        DROPDOWN_SELECT: ' - ',
        SELECTOR_TEXT: 'SELECT YOUR MODE',
        SELECTOR_TEXT_HINT: '(YOU CAN CHANGE IT LATER WITH THE "A" ICON)',
        COMING_SOON: 'COMING SOON',
        ARROW: '>',
        BUTTON_METRICS: 'METRICS',
        BUTTON_EDIT: 'EDIT',
        BUTTON_MODE: 'MODE',
        BUTTON_SHARE: 'SHARE',
        MODE_1: 'Mode 1',
        MODE_2: 'Mode 2',
        MODE_3: 'Mode 3',
        SLIDER: 'TINT',
        DETAIL: 'DETAIL',
        LINE: 'LINE',
        BACKGROUND: 'BACK',
        MESSAGE_ANDROID: 'Instagram\'s browser might block downloads. Tap below to open this page in Chrome:',
        MESSAGE_BROWSER: 'Open in browser'
    },
    it: {
        MONTH_1: 'Gennaio',
        MONTH_2: 'Febbraio',
        MONTH_3: 'Marzo',
        MONTH_4: 'Aprile',
        MONTH_5: 'Maggio',
        MONTH_6: 'Giugno',
        MONTH_7: 'Luglio',
        MONTH_8: 'Agosto',
        MONTH_9: 'Settembre',
        MONTH_10: 'Ottobre',
        MONTH_11: 'Novembre',
        MONTH_12: 'Dicembre',
        HOMEPAGE_SHARE_BY: 'CONDIVIDI LA TUA ATTIVITÀ TRAMITE',
        HOMEPAGE_LOGIN_STRAVA: 'LOGIN A STRAVA',
        HOMEPAGE_OR: 'O',
        HOMEPAGE_LOAD: 'CARICA UN GPX',
        HOMEPAGE_PER: 'X',
        HOMEPAGE_BACK: '< INDIETRO',
        HOMEPAGE_SELECT_ACTIVITY: 'SELEZIONA UN\'ATTIVITÀ',
        HOMEPAGE_BEFORE_START: 'PRIMA DI INIZIARE DEVI CARICARE ALMENO UN\'ATTIVITÀ SU STRAVA',
        BUTTON_TITLE: 'TITOLO',
        BUTTON_DATE: 'DATA',
        BUTTON_DISTANCE: 'DISTANZA',
        BUTTON_DURATION: 'DURATA',
        BUTTON_MOVING_TIME: 'TEMPO TRASCORSO',
        BUTTON_ELEVATION: 'DISLIVELLO',
        BUTTON_ELEVATION_GAIN: 'DISLIVELLO',
        BUTTON_AVERAGE: 'MEDIA',
        BUTTON_PACE: 'PASSO',
        BUTTON_AVERAGE_PACE: 'PASSO MEDIO',
        BUTTON_VELOCITA_AVERAGE: 'VELOCITA\' MEDIA',
        BUTTON_POWER: 'POTENZA',
        BUTTON_AVERGAE_POWER: 'POTENZA MEDIA',
        BUTTON_COORDINATES: 'COORDINATE',
        BUTTON_CALORIES: 'CALORIE',
        BUTTON_SWITCH: 'SCAMBIA TESTO',
        BUTTON_SWITCH_ALTITUDE: 'SPOSTA PROFILO',
        IMAGE_DISTANCE: 'Distanza',
        IMAGE_DURATION: 'Durata',
        IMAGE_MOVING_TIME: 'Tempo In Movimento',
        IMAGE_ELEVATION: 'Dislivello',
        IMAGE_ELEVATION_GAIN: 'Dislivello',
        IMAGE_AVERAGE: 'Media',
        IMAGE_PACE: 'Passo',
        IMAGE_AVERAGE_PACE: 'Passo Medio',
        IMAGE_AVERAGE_SPEED: 'Velocità Media',
        IMAGE_POWER: 'Potenza',
        IMAGE_AVERAGE_POWER: 'Potenza Media',
        IMAGE_COORDINATES: 'Coordinate',
        IMAGE_CALORIES: 'Calorie',
        NAME_APP: 'TRACELINER © ' + new Date().getFullYear(),
        CREATED_BY: 'Creato con ❤️ da Giovanni Maggi',
        MODAL_TEXT: 'Salva la tua versione preferita!',
        MODAL_GUIDE: 'Quella con lo sfondo può essere condivisa direttamente su IG mentre quella con sfondo trasparente deve essere prima salvata nella galleria e poi inserita come livello nelle storie!',
        MODAL_COMPLETE: 'COMPLETA',
        MODAL_CONTOUR: 'CONTORNO',
        MODAL_ERROR: 'Qualcosa è andato storto rigenera l\'immagine',
        DROPDOWN_SELECT: ' - ',
        SELECTOR_TEXT: 'SELEZIONA LA MODE CHE PREFERISCI',
        SELECTOR_TEXT_HINT: '(LA PUOI CAMBIARE ANCHE DOPO CON L\'ICONA "A")',
        COMING_SOON: 'COMING SOON',
        ARROW: '>',
        BUTTON_METRICS: 'METRICS',
        BUTTON_EDIT: 'MODIFICA',
        BUTTON_MODE: 'MODALITA\'',
        BUTTON_SHARE: 'CONDIVIDI',
        MODE_1: 'Mode 1',
        MODE_2: 'Mode 2',
        MODE_3: 'Mode 3',
        SLIDER: 'FILTRO',
        DETAIL: 'DETTAGLI',
        LINE: 'LINE',
        BACKGROUND: 'SFONDO',
        MESSAGE_ANDROID: 'Instagram potrebbe bloccare i download. Clicca sotto per aprire traceliner nel tuo browser:',
        MESSAGE_BROWSER: 'Apri nel browser'
    }
}

const languages = ['en','it']

const languagesRules = {
    'en' : {
        dayFirst: false
    },
    'it' : {
        dayFirst: true
    }
}

export {vocabulary, languages, languagesRules}