const vocabulary = {
    en: {
        HOMEPAGE_SHARE_BY: 'SHARE YOUR RIDE BY',
        HOMEPAGE_LOGIN_STRAVA: 'LOGIN TO STRAVA',
        HOMEPAGE_OR: 'OR',
        HOMEPAGE_LOAD: 'LOAD A GPX',
        HOMEPAGE_PER: 'X',
        HOMEPAGE_BACK: 'BACK',
        HOMEPAGE_SELECT_ACTIVITY: 'SELECT AN ACTIVITY',
        HOMEPAGE_BEFORE_START: 'BEFORE YOU CAN START YOU HAVE TO LOAD SOME ACTIVITIES',
    },
    it: {
        HOMEPAGE_SHARE_BY: 'CONDIVIDI LA TUA ATTIVITÀ TRAMITE',
        HOMEPAGE_LOGIN_STRAVA: 'LOGIN A STRAVA',
        HOMEPAGE_OR: 'O',
        HOMEPAGE_LOAD: 'CARICA UN GPX',
        HOMEPAGE_PER: 'X',
        HOMEPAGE_BACK: 'INDIETRO',
        HOMEPAGE_SELECT_ACTIVITY: 'SELEZIONA UN\'ATTIVITÀ',
        HOMEPAGE_BEFORE_START: 'PRIMA DI INIZIARE DEVI CARICARE ALMENO UN\'ATTIVITÀ SU STRAVA',
    }
}

export default vocabulary